# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
np.arange(10) #arange it will print the value within interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [8]:
np.arange(10,20,5)

array([10, 15])

In [9]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [10]:
np.zeros(3) #parameter tunning

array([0., 0., 0.])

In [11]:
np.zeros(5,dtype=int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [12]:
np.zeros([2,2],dtype=int) #2d array

array([[0, 0],
       [0, 0]])

In [13]:
np.zeros([5,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [16]:
np.ones([3,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(20,10)

array([], dtype=int64)

In [21]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [22]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [23]:
np.threes(3)

AttributeError: module 'numpy' has no attribute 'threes'

In [24]:
random.rand(3,2)

NameError: name 'random' is not defined

In [25]:
np.random.rand(2)

array([0.83463737, 0.0842724 ])

In [26]:
np.random.rand(5)

array([0.72089752, 0.7654419 , 0.97476718, 0.51153788, 0.33347894])

In [27]:
np.random.rand(3,2)

array([[0.59412966, 0.90293239],
       [0.48411318, 0.33005975],
       [0.48600245, 0.22940838]])

In [32]:
np.random.randint(4)

1

In [35]:
np.random.randint(5,10)

8

In [37]:
np.random.randint(5,10,3)

array([9, 8, 9], dtype=int32)

In [38]:
ran = np.random.randint(5,10,3)
print(ran)

[7 6 9]


In [40]:
otp = np.random.randint(5,10,4)
print(otp)

[6 7 5 8]


In [42]:
arr0 = np.random.randint(10,40,(10,10))
print(arr0)

[[11 23 18 35 38 23 21 39 22 17]
 [38 15 12 22 28 39 27 26 12 21]
 [12 21 14 29 37 34 19 17 20 28]
 [13 32 15 32 32 37 17 37 10 34]
 [15 25 13 22 15 12 39 33 10 29]
 [29 29 39 22 24 28 20 32 33 14]
 [17 36 18 16 22 10 19 29 36 28]
 [15 28 22 18 24 31 23 20 36 28]
 [34 26 19 13 38 32 10 25 35 13]
 [37 32 35 10 31 34 25 31 10 33]]


In [43]:
arr0

array([[11, 23, 18, 35, 38, 23, 21, 39, 22, 17],
       [38, 15, 12, 22, 28, 39, 27, 26, 12, 21],
       [12, 21, 14, 29, 37, 34, 19, 17, 20, 28],
       [13, 32, 15, 32, 32, 37, 17, 37, 10, 34],
       [15, 25, 13, 22, 15, 12, 39, 33, 10, 29],
       [29, 29, 39, 22, 24, 28, 20, 32, 33, 14],
       [17, 36, 18, 16, 22, 10, 19, 29, 36, 28],
       [15, 28, 22, 18, 24, 31, 23, 20, 36, 28],
       [34, 26, 19, 13, 38, 32, 10, 25, 35, 13],
       [37, 32, 35, 10, 31, 34, 25, 31, 10, 33]], dtype=int32)

In [44]:
arr1 = np.random.randint(1,5,(3,3))
print(arr1)

[[1 4 1]
 [4 3 3]
 [3 3 3]]


# indexing , slicing in array

In [45]:
arr1[:]

array([[1, 4, 1],
       [4, 3, 3],
       [3, 3, 3]], dtype=int32)

In [46]:
len(arr1)

3

In [47]:
arr1.shape

(3, 3)

In [48]:
arr0.shape

(10, 10)

In [49]:
len(arr0)

10

In [50]:
arr1

array([[1, 4, 1],
       [4, 3, 3],
       [3, 3, 3]], dtype=int32)

In [52]:
arr1[0] # print row

array([1, 4, 1], dtype=int32)

In [53]:
arr1[1]

array([4, 3, 3], dtype=int32)

In [54]:
arr1

array([[1, 4, 1],
       [4, 3, 3],
       [3, 3, 3]], dtype=int32)

In [55]:
arr1[:,1]

array([4, 3, 3], dtype=int32)

In [56]:
arr1[:,2]

array([1, 3, 3], dtype=int32)

In [57]:
arr1

array([[1, 4, 1],
       [4, 3, 3],
       [3, 3, 3]], dtype=int32)

In [58]:
arr1[0]

array([1, 4, 1], dtype=int32)

In [59]:
v = arr1[1,2]
print(v)

3


In [60]:
arr0

array([[11, 23, 18, 35, 38, 23, 21, 39, 22, 17],
       [38, 15, 12, 22, 28, 39, 27, 26, 12, 21],
       [12, 21, 14, 29, 37, 34, 19, 17, 20, 28],
       [13, 32, 15, 32, 32, 37, 17, 37, 10, 34],
       [15, 25, 13, 22, 15, 12, 39, 33, 10, 29],
       [29, 29, 39, 22, 24, 28, 20, 32, 33, 14],
       [17, 36, 18, 16, 22, 10, 19, 29, 36, 28],
       [15, 28, 22, 18, 24, 31, 23, 20, 36, 28],
       [34, 26, 19, 13, 38, 32, 10, 25, 35, 13],
       [37, 32, 35, 10, 31, 34, 25, 31, 10, 33]], dtype=int32)

In [61]:
arr0[-7]

array([13, 32, 15, 32, 32, 37, 17, 37, 10, 34], dtype=int32)

In [62]:
arr0[:,-7]

array([35, 22, 29, 32, 22, 22, 16, 18, 13, 10], dtype=int32)

In [63]:
arr0

array([[11, 23, 18, 35, 38, 23, 21, 39, 22, 17],
       [38, 15, 12, 22, 28, 39, 27, 26, 12, 21],
       [12, 21, 14, 29, 37, 34, 19, 17, 20, 28],
       [13, 32, 15, 32, 32, 37, 17, 37, 10, 34],
       [15, 25, 13, 22, 15, 12, 39, 33, 10, 29],
       [29, 29, 39, 22, 24, 28, 20, 32, 33, 14],
       [17, 36, 18, 16, 22, 10, 19, 29, 36, 28],
       [15, 28, 22, 18, 24, 31, 23, 20, 36, 28],
       [34, 26, 19, 13, 38, 32, 10, 25, 35, 13],
       [37, 32, 35, 10, 31, 34, 25, 31, 10, 33]], dtype=int32)

In [64]:
arr0[3:4,2:6]

array([[15, 32, 32, 37]], dtype=int32)

In [67]:
arr1

array([[1, 4, 1],
       [4, 3, 3],
       [3, 3, 3]], dtype=int32)

In [68]:
arr1[1]

array([4, 3, 3], dtype=int32)

In [69]:
arr1[1,2]

np.int32(3)

In [70]:
arr1[1:2]

array([[4, 3, 3]], dtype=int32)