In [2]:
import numpy as np

In [4]:
arr0 = np.random.randint(10,40,(10,10))
print(arr0)

[[21 26 20 32 36 21 31 15 12 25]
 [10 11 35 19 26 31 30 12 32 10]
 [37 11 20 34 30 30 11 39 22 18]
 [37 13 33 31 17 28 26 28 36 22]
 [18 24 36 39 34 11 13 38 35 12]
 [17 33 36 37 20 22 27 10 30 18]
 [15 13 29 34 24 23 35 31 13 31]
 [28 28 25 34 25 15 29 37 30 10]
 [11 37 13 22 25 27 21 13 11 35]
 [10 14 38 20 17 32 13 35 16 10]]


In [5]:
arr1 = np.random.randint(1,5,(3,3))
print(arr1)

[[3 1 2]
 [4 3 4]
 [4 2 2]]


In [6]:
arr0[::3]

array([[21, 26, 20, 32, 36, 21, 31, 15, 12, 25],
       [37, 13, 33, 31, 17, 28, 26, 28, 36, 22],
       [15, 13, 29, 34, 24, 23, 35, 31, 13, 31],
       [10, 14, 38, 20, 17, 32, 13, 35, 16, 10]], dtype=int32)

In [7]:
arr0[0:10:5]

array([[21, 26, 20, 32, 36, 21, 31, 15, 12, 25],
       [17, 33, 36, 37, 20, 22, 27, 10, 30, 18]], dtype=int32)

In [8]:
arr0[::-1]

array([[10, 14, 38, 20, 17, 32, 13, 35, 16, 10],
       [11, 37, 13, 22, 25, 27, 21, 13, 11, 35],
       [28, 28, 25, 34, 25, 15, 29, 37, 30, 10],
       [15, 13, 29, 34, 24, 23, 35, 31, 13, 31],
       [17, 33, 36, 37, 20, 22, 27, 10, 30, 18],
       [18, 24, 36, 39, 34, 11, 13, 38, 35, 12],
       [37, 13, 33, 31, 17, 28, 26, 28, 36, 22],
       [37, 11, 20, 34, 30, 30, 11, 39, 22, 18],
       [10, 11, 35, 19, 26, 31, 30, 12, 32, 10],
       [21, 26, 20, 32, 36, 21, 31, 15, 12, 25]], dtype=int32)

In [9]:
arr0[::-3]

array([[10, 14, 38, 20, 17, 32, 13, 35, 16, 10],
       [15, 13, 29, 34, 24, 23, 35, 31, 13, 31],
       [37, 13, 33, 31, 17, 28, 26, 28, 36, 22],
       [21, 26, 20, 32, 36, 21, 31, 15, 12, 25]], dtype=int32)

In [10]:
arr1

array([[3, 1, 2],
       [4, 3, 4],
       [4, 2, 2]], dtype=int32)

In [11]:
arr1[1,2]

np.int32(4)

In [12]:
arr1[1:2]

array([[4, 3, 4]], dtype=int32)

In [13]:
arr1[:,2]

array([2, 4, 2], dtype=int32)

# reshaping

In [15]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [17]:
arr = np.array(my_list)
print(arr)

[0 1 2 3 4 5]


In [18]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 6 into shape (4,4)

In [21]:
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [24]:
arr1

array([[3, 1, 2],
       [4, 3, 4],
       [4, 2, 2]], dtype=int32)

In [25]:
arr1[0:2,1:3]

array([[1, 2],
       [3, 4]], dtype=int32)

# masking or filter in matrix

In [26]:
arr0

array([[21, 26, 20, 32, 36, 21, 31, 15, 12, 25],
       [10, 11, 35, 19, 26, 31, 30, 12, 32, 10],
       [37, 11, 20, 34, 30, 30, 11, 39, 22, 18],
       [37, 13, 33, 31, 17, 28, 26, 28, 36, 22],
       [18, 24, 36, 39, 34, 11, 13, 38, 35, 12],
       [17, 33, 36, 37, 20, 22, 27, 10, 30, 18],
       [15, 13, 29, 34, 24, 23, 35, 31, 13, 31],
       [28, 28, 25, 34, 25, 15, 29, 37, 30, 10],
       [11, 37, 13, 22, 25, 27, 21, 13, 11, 35],
       [10, 14, 38, 20, 17, 32, 13, 35, 16, 10]], dtype=int32)

In [27]:
arr0 < 20

array([[False, False, False, False, False, False, False,  True,  True,
        False],
       [ True,  True, False,  True, False, False, False,  True, False,
         True],
       [False,  True, False, False, False, False,  True, False, False,
         True],
       [False,  True, False, False,  True, False, False, False, False,
        False],
       [ True, False, False, False, False,  True,  True, False, False,
         True],
       [ True, False, False, False, False, False, False,  True, False,
         True],
       [ True,  True, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False,  True, False, False, False,
         True],
       [ True, False,  True, False, False, False, False,  True,  True,
        False],
       [ True,  True, False, False,  True, False,  True, False,  True,
         True]])

In [28]:
arr0[arr0 < 20]

array([15, 12, 10, 11, 19, 12, 10, 11, 11, 18, 13, 17, 18, 11, 13, 12, 17,
       10, 18, 15, 13, 13, 15, 10, 11, 13, 13, 11, 10, 14, 17, 13, 16, 10],
      dtype=int32)

In [29]:
arr0[arr0 == 20]

array([20, 20, 20, 20], dtype=int32)

In [30]:
arr0[arr0!=20]

array([21, 26, 32, 36, 21, 31, 15, 12, 25, 10, 11, 35, 19, 26, 31, 30, 12,
       32, 10, 37, 11, 34, 30, 30, 11, 39, 22, 18, 37, 13, 33, 31, 17, 28,
       26, 28, 36, 22, 18, 24, 36, 39, 34, 11, 13, 38, 35, 12, 17, 33, 36,
       37, 22, 27, 10, 30, 18, 15, 13, 29, 34, 24, 23, 35, 31, 13, 31, 28,
       28, 25, 34, 25, 15, 29, 37, 30, 10, 11, 37, 13, 22, 25, 27, 21, 13,
       11, 35, 10, 14, 38, 17, 32, 13, 35, 16, 10], dtype=int32)

In [31]:
arr0[arr0>35]

array([36, 37, 39, 37, 36, 36, 39, 38, 36, 37, 37, 37, 38], dtype=int32)

In [32]:
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
max(arr)

np.int64(5)

In [34]:
min(arr)

np.int64(0)

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [37]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [39]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [41]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [42]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [43]:
np.arange(30,20)

array([], dtype=int64)

In [44]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [45]:
np.arange(10,10)

array([], dtype=int64)

In [46]:
np.arange()

TypeError: arange() requires stop to be specified.

In [47]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [48]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [49]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [50]:
np.zeros(10) #parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.zeros(5,dtype=int) #hperparameter tunning

array([0, 0, 0, 0, 0])

In [54]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [55]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [56]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [57]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [61]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [62]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [63]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [70]:
 print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [71]:
n

(6, 7)

In [72]:
n1

(6, 8)

In [73]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
np.ones(3)

array([1., 1., 1.])

In [75]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [77]:
np.ones(4)

array([1., 1., 1., 1.])

In [78]:
n

(6, 7)

In [79]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [81]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [83]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [84]:
range(5)

range(0, 5)

In [85]:
r = range(5)
r

range(0, 5)

In [86]:
for i in r:
    print(i)

0
1
2
3
4


In [87]:
list(range(5))

[0, 1, 2, 3, 4]

In [88]:
range(1,10)

range(1, 10)

In [89]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
list(range(1,10,3))

[1, 4, 7]

In [91]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [92]:
rand(3,2)

NameError: name 'rand' is not defined

In [93]:
random.rand(3,2)

NameError: name 'random' is not defined

In [94]:
np.random.rand(5)

array([0.4120049 , 0.77358309, 0.69634147, 0.82841623, 0.08894756])

In [96]:
np.random.randint(5)

2

In [97]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [98]:
np.random.rand(3,5)

array([[0.27443967, 0.00730698, 0.78232017, 0.63324805, 0.26786638],
       [0.63295269, 0.15126034, 0.42340471, 0.91545302, 0.79371499],
       [0.11644046, 0.588569  , 0.3960991 , 0.41980074, 0.2507756 ]])

In [103]:
np.random.randint(4,6)

4

In [104]:
np.random.randint(4)

1

In [105]:
np.random.rand(4)

array([0.23072916, 0.00958784, 0.67000513, 0.58595716])

In [107]:
np.random.randint(10,40,(10,10))

array([[13, 27, 29, 13, 27, 18, 28, 30, 25, 34],
       [21, 18, 14, 33, 39, 37, 39, 37, 15, 33],
       [15, 25, 32, 27, 18, 27, 27, 30, 28, 12],
       [19, 22, 39, 10, 12, 35, 28, 37, 22, 15],
       [30, 11, 29, 17, 37, 39, 30, 32, 35, 10],
       [14, 21, 10, 15, 22, 35, 17, 37, 17, 14],
       [21, 25, 36, 27, 31, 15, 15, 27, 25, 32],
       [28, 25, 17, 10, 32, 20, 13, 18, 26, 11],
       [14, 17, 23, 31, 31, 14, 18, 12, 13, 37],
       [12, 32, 35, 29, 24, 12, 27, 26, 13, 16]], dtype=int32)

In [108]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
range(1,13)

range(1, 13)

In [110]:
list(range(1,13))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [111]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# slicing in matric

In [114]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 10, 11, 12],
       [13, 15, 10, 19],
       [10, 15, 18, 13],
       [12, 13, 16, 18],
       [16, 13, 11, 17]], dtype=int32)

In [115]:
type(b)

numpy.ndarray

In [116]:
b

array([[16, 10, 11, 12],
       [13, 15, 10, 19],
       [10, 15, 18, 13],
       [12, 13, 16, 18],
       [16, 13, 11, 17]], dtype=int32)

In [117]:
b[:]

array([[16, 10, 11, 12],
       [13, 15, 10, 19],
       [10, 15, 18, 13],
       [12, 13, 16, 18],
       [16, 13, 11, 17]], dtype=int32)

In [118]:
b[1:3]

array([[13, 15, 10, 19],
       [10, 15, 18, 13]], dtype=int32)

In [119]:
b[1,2]

np.int32(10)

In [120]:
b[1,3]

np.int32(19)

In [121]:
b[1,-1]

np.int32(19)

In [122]:
b[2:3]

array([[10, 15, 18, 13]], dtype=int32)

In [123]:
b[0:-2]

array([[16, 10, 11, 12],
       [13, 15, 10, 19],
       [10, 15, 18, 13]], dtype=int32)

In [124]:
b

array([[16, 10, 11, 12],
       [13, 15, 10, 19],
       [10, 15, 18, 13],
       [12, 13, 16, 18],
       [16, 13, 11, 17]], dtype=int32)

In [125]:
b[0,2]

np.int32(11)

In [126]:
b[-5,3]

np.int32(12)

In [127]:
b[-5,-3]

np.int32(10)

In [128]:
b[-4,2]

np.int32(10)

In [129]:
b[-4:2]

array([[13, 15, 10, 19]], dtype=int32)

In [130]:
b[:]

array([[16, 10, 11, 12],
       [13, 15, 10, 19],
       [10, 15, 18, 13],
       [12, 13, 16, 18],
       [16, 13, 11, 17]], dtype=int32)

# operations

In [132]:
a = np.random.randint(10,20,10) #10,20 k bich mein 10 random numbers
a

array([10, 12, 16, 12, 13, 11, 13, 19, 19, 17], dtype=int32)

In [133]:
id(a)

1892840961104

In [134]:
arr

array([0, 1, 2, 3, 4, 5])

In [135]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [78, 65, 78, 82, 35, 63, 89, 90, 30, 61],
       [32, 23,  6, 81, 66, 62,  1, 50,  7, 99]], dtype=int32)

In [136]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [137]:
arr[:4]

array([0, 1, 2, 3])

In [138]:
arr2[:]

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [78, 65, 78, 82, 35, 63, 89, 90, 30, 61],
       [32, 23,  6, 81, 66, 62,  1, 50,  7, 99]], dtype=int32)

In [139]:
arr2[0:5]

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97]], dtype=int32)

In [140]:
arr2

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [78, 65, 78, 82, 35, 63, 89, 90, 30, 61],
       [32, 23,  6, 81, 66, 62,  1, 50,  7, 99]], dtype=int32)

In [141]:
arr2[-5,5]

np.int32(5)

In [142]:
arr2[-5,-5]

np.int32(5)

In [143]:
arr2[-1,-2]

np.int32(7)

In [144]:
arr2[::-1]

array([[32, 23,  6, 81, 66, 62,  1, 50,  7, 99],
       [78, 65, 78, 82, 35, 63, 89, 90, 30, 61],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [66,  7, 82, 85, 37, 95, 25, 60, 37, 91]], dtype=int32)

In [145]:
arr2

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [78, 65, 78, 82, 35, 63, 89, 90, 30, 61],
       [32, 23,  6, 81, 66, 62,  1, 50,  7, 99]], dtype=int32)

In [146]:
arr2[::-2]

array([[32, 23,  6, 81, 66, 62,  1, 50,  7, 99],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74]], dtype=int32)

In [147]:
arr2[::-3]

array([[32, 23,  6, 81, 66, 62,  1, 50,  7, 99],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [66,  7, 82, 85, 37, 95, 25, 60, 37, 91]], dtype=int32)

In [148]:
arr2

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [22, 47, 15, 17, 60, 11, 59, 80, 41, 97],
       [97,  4, 28, 53,  9,  5, 93, 46, 83, 85],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [40, 68, 74, 21, 11, 83, 99, 55, 48, 31],
       [78, 65, 78, 82, 35, 63, 89, 90, 30, 61],
       [32, 23,  6, 81, 66, 62,  1, 50,  7, 99]], dtype=int32)

In [149]:
arr2[0:10:3]

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 4, 71, 28,  8, 24,  0, 16, 76, 57,  6],
       [ 5,  9, 55, 81, 84, 69, 69,  9, 89, 67],
       [32, 23,  6, 81, 66, 62,  1, 50,  7, 99]], dtype=int32)

In [150]:
arr2[:3]

array([[66,  7, 82, 85, 37, 95, 25, 60, 37, 91],
       [ 6, 37, 82, 24, 40, 40, 80, 69, 46, 74],
       [20,  3, 51, 98, 32, 93, 60, 53,  2, 76]], dtype=int32)

In [151]:
arr.max()

np.int64(5)

In [152]:
arr.min

<function ndarray.min>

In [153]:
arr.mean()

np.float64(2.5)

In [154]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [155]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# without work on import* can you please find the median , mode

In [156]:
arr

array([0, 1, 2, 3, 4, 5])

In [157]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [158]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [159]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [160]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [161]:
arr

array([0, 1, 2, 3, 4, 5])

In [166]:
arr.reshape(2,3,order='C') #default left to right and then top to bottom

array([[0, 1, 2],
       [3, 4, 5]])

In [164]:
arr.reshape(2,3,order='F') #fortran fill array top to bottom first then left to right

array([[0, 2, 4],
       [1, 3, 5]])

In [167]:
arr.reshape(2,3,order='A') # A gives almost c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [170]:
# importing numpy package
import numpy as np
# creating a numpy array
num_array = np.arange(100).reshape(20,5)
print(num_array)
# display in fortran order
print("\n F type array:")
for num_array in np.nditer(num_array,order='F'):
    print(num_array,end=' ')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

 F type array:
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 2 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97 3 8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98 4 9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99 

# indexing

In [172]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
row = 4
col = 5
col

5

In [174]:
row

4

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[row,col]

np.int64(45)

In [177]:
mat[4,5]

np.int64(45)

In [178]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
col = 6

In [180]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [182]:
# width slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [184]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [185]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [186]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [187]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [188]:
row

4

In [189]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [190]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [193]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [194]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [195]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [196]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [198]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [199]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [200]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [206]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [207]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [208]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [211]:
mat[0,1]

np.int64(1)

In [212]:
mat[1,6]

np.int64(16)

In [213]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [214]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [215]:
mat[1:2,2:4]

array([[12, 13]])

# masking

In [216]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
id(mat)

1892844996720

In [218]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [219]:
mat[mat==50]

array([50])

In [220]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [221]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# python program to generate otp

In [224]:
import random
def generate_otp(length=4):
    """Generate a numeric otp of specified length"""
    digits = '012345'
    otp = ''.join(random.choice(digits)for _ in range(length))
    return otp
# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")   

Your OTP is: 5324
