In [1]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.arange(10) #print the value within interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [11]:
np.arange(10,20,5)

array([10, 15])

In [12]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [14]:
np.zeros(5) #parameter tunning

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int)  #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [16]:
np.zeros([2,2],dtype=int) #2d array

array([[0, 0],
       [0, 0]])

In [18]:
np.zeros([5,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones([3,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.arange(20,10)

array([], dtype=int64)

In [24]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [26]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [27]:
random.rand(3,2)

NameError: name 'random' is not defined

In [28]:
np.random.rand(2)

array([0.94515992, 0.34336324])

In [35]:
np.random.rand(3,2)

array([[0.06396752, 0.38876277],
       [0.5739864 , 0.63172267],
       [0.94894694, 0.86555756]])

In [34]:
np.random.randint(3)

1

In [36]:
np.random.randint(5,10)

5

In [39]:
np.random.randint(5,10,3)

array([5, 9, 7], dtype=int32)

In [41]:
ran = np.random.randint(5,10,3)
print(ran)

[5 9 9]


In [46]:
otp=np.random.randint(5,10,4)
print(otp)

[7 5 9 9]


In [45]:
otp=np.random.randint(5,10,4)
print(otp)

[7 8 9 5]


In [47]:
np.random.randint(10,40,(10,10))

array([[33, 37, 17, 35, 26, 23, 32, 28, 38, 32],
       [38, 26, 29, 26, 19, 24, 18, 10, 36, 31],
       [32, 24, 16, 26, 14, 16, 26, 16, 16, 35],
       [10, 17, 29, 29, 35, 34, 25, 10, 33, 37],
       [14, 36, 32, 19, 23, 19, 14, 15, 29, 29],
       [38, 39, 23, 32, 13, 20, 25, 16, 27, 24],
       [17, 37, 13, 16, 20, 35, 21, 39, 15, 17],
       [35, 35, 14, 21, 38, 38, 39, 39, 35, 26],
       [23, 26, 10, 18, 10, 39, 10, 25, 34, 37],
       [32, 30, 31, 37, 16, 22, 39, 38, 38, 17]], dtype=int32)

# , indexing,slicing in array

In [49]:
arr1=np.random.randint(1,5,(3,3))
print(arr1)


[[2 4 3]
 [4 2 2]
 [2 1 2]]


In [50]:
arr1[:]

array([[2, 4, 3],
       [4, 2, 2],
       [2, 1, 2]], dtype=int32)

In [51]:
len(arr1)

3

In [52]:
arr1.shape

(3, 3)

In [53]:
arr1[0]

array([2, 4, 3], dtype=int32)

In [54]:
arr1[1]

array([4, 2, 2], dtype=int32)

In [55]:
arr1[2]

array([2, 1, 2], dtype=int32)

In [56]:
arr1[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [59]:
arr1

array([[2, 4, 3],
       [4, 2, 2],
       [2, 1, 2]], dtype=int32)

In [58]:
arr1[:,0]

array([2, 4, 2], dtype=int32)

In [60]:
arr1[:,1]

array([4, 2, 1], dtype=int32)

In [61]:
arr1[0]

array([2, 4, 3], dtype=int32)

In [66]:
arr1

array([[2, 4, 3],
       [4, 2, 2],
       [2, 1, 2]], dtype=int32)

In [67]:
arr1[1,2]

np.int32(2)

In [68]:
v=arr1(1,2)
print(v)

TypeError: 'numpy.ndarray' object is not callable

In [69]:
v = arr1[1,2]
print(v)

2


In [72]:
arr1

array([[2, 4, 3],
       [4, 2, 2],
       [2, 1, 2]], dtype=int32)

In [73]:
arr1[1]

array([4, 2, 2], dtype=int32)

In [75]:
arr1[0:2]

array([[2, 4, 3],
       [4, 2, 2]], dtype=int32)

In [76]:
 arr1[1:2] #1 first row and 2 means columns 

array([[4, 2, 2]], dtype=int32)

In [81]:
arr1=np.random.randint(1,5,(3,3))
print(arr1)


[[1 4 1]
 [2 4 2]
 [1 3 1]]


In [82]:
arr1[::1]

array([[1, 4, 1],
       [2, 4, 2],
       [1, 3, 1]], dtype=int32)

In [83]:
arr1[::2]

array([[1, 4, 1],
       [1, 3, 1]], dtype=int32)

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [84]:
arr1[::3]

array([[1, 4, 1]], dtype=int32)

In [ ]:
arr1[0:3:2